/**
 * audit/routes.ts — Phase 15 Cap.2.
 *
 * Central list of user-visible routes the screenshot harness drives.
 * Generated by walking `app/**\/page.tsx` on 2026-04-23.
 *
 * Rules:
 *   - Only `page.tsx` under `app/` counts. API routes (`route.ts`) are
 *     excluded — the harness is visual-only.
 *   - Route groups like `(group)/` are stripped from the path because
 *     they never appear in URLs.
 *   - Dynamic segments (`[slug]`, `[num]`) are skipped for now — they
 *     need representative fixture IDs before they can be captured. See
 *     TODO at bottom of file for the shortlist.
 *
 * Persona gate:
 *   - `authRequired` mirrors middleware.ts. `/`, `/signin`, `/403` are
 *     the three unauthenticated pages; everything else demands a cookie.
 *   - `personas` is the set of persona IDs whose captures include this
 *     route — admin-gated paths list only "admin"; general paths list
 *     all 6. See audit/personas.ts for the persona dictionary.
 */

export type PersonaId =
  | "founder-first-time"
  | "founder-returning"
  | "operator"
  | "senior-dev"
  | "admin"
  | "live-spectator"

export interface RouteEntry {
  /** Absolute URL path as the browser sees it, e.g. "/build/security". */
  path: string
  /** Filesystem-safe slug used for screenshot filenames. */
  slug: string
  /** True when middleware.ts redirects unauthenticated users away. */
  authRequired: boolean
  /** Personas whose captures include this route. */
  personas: PersonaId[]
}

// Convenience — all six personas. Any route that isn't admin-gated gets
// this set. Admin-gated routes override with a smaller set.
const ALL_PERSONAS: PersonaId[] = [
  "founder-first-time",
  "founder-returning",
  "operator",
  "senior-dev",
  "admin",
  "live-spectator",
]

// Routes where the middleware only lets admins through. First-time
// visitors and viewer roles would see /403 instead, so capturing them
// across all 6 personas wastes cycles — limit to admin only.
const ADMIN_ONLY: PersonaId[] = ["admin"]

// Operator-gated routes (see middleware.ts → /build/security/audit).
const OPERATOR_UP: PersonaId[] = ["operator", "admin", "live-spectator"]

export const ROUTES: RouteEntry[] = [
  // ── Public / unauthenticated ──────────────────────────────────────────
  { path: "/", slug: "root", authRequired: false, personas: ALL_PERSONAS },
  { path: "/signin", slug: "signin", authRequired: false, personas: ALL_PERSONAS },
  { path: "/403", slug: "403", authRequired: false, personas: ALL_PERSONAS },

  // ── Top-level authenticated surfaces ──────────────────────────────────
  { path: "/plan", slug: "plan", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build", slug: "build", authRequired: true, personas: ALL_PERSONAS },
  { path: "/chat", slug: "chat", authRequired: true, personas: ALL_PERSONAS },
  { path: "/floor", slug: "floor", authRequired: true, personas: ALL_PERSONAS },
  { path: "/floor/popout", slug: "floor-popout", authRequired: true, personas: ALL_PERSONAS },
  { path: "/memory", slug: "memory", authRequired: true, personas: ALL_PERSONAS },
  { path: "/metrics", slug: "metrics", authRequired: true, personas: ALL_PERSONAS },

  // ── /build sub-pages ──────────────────────────────────────────────────
  { path: "/build/queue", slug: "build-queue", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/changes", slug: "build-changes", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/agents", slug: "build-agents", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/workflows", slug: "build-workflows", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/workflows/new", slug: "build-workflows-new", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/schedule", slug: "build-schedule", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/schedule/new", slug: "build-schedule-new", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/skills", slug: "build-skills", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/skills/installed", slug: "build-skills-installed", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/security", slug: "build-security", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/security/secrets", slug: "build-security-secrets", authRequired: true, personas: ALL_PERSONAS },
  { path: "/build/security/skills", slug: "build-security-skills", authRequired: true, personas: ALL_PERSONAS },

  // Operator-or-up: audit log.
  { path: "/build/security/audit", slug: "build-security-audit", authRequired: true, personas: OPERATOR_UP },

  // Admin-only: role manager.
  { path: "/build/admin/roles", slug: "build-admin-roles", authRequired: true, personas: ADMIN_ONLY },
]

// TODO(audit-cap2.1): dynamic-segment routes require representative IDs
// before capture. When fixtures grow to seed these, add entries like:
//   /build/phase/15                       (phase detail)
//   /build/workflows/<first-workflow-id>  (workflow detail)
//   /build/skills/<first-installed-slug>  (skill detail)
// For now we capture the list views above and leave the detail views
// for a follow-up wave.
